"""add procurement returns billing

Revision ID: 32e1cd1122a8
Revises: 815dac684b5d
Create Date: 2026-08-18 02:37:01.385117

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "32e1cd1122a8"
down_revision: Union[str, Sequence[str], None] = "815dac684b5d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "payment",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("payment_number", sa.String(length=50), nullable=False),
        sa.Column("payer_organization_id", sa.BigInteger(), nullable=False),
        sa.Column("payee_organization_id", sa.BigInteger(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("payment_date", sa.Date(), nullable=False),
        sa.Column("amount", sa.Numeric(precision=16, scale=2), nullable=False),
        sa.Column(
            "unallocated_amount", sa.Numeric(precision=16, scale=2), nullable=False
        ),
        sa.Column("method", sa.String(length=30), nullable=False),
        sa.Column("reference", sa.String(length=100), nullable=True),
        sa.Column("created_by_account_id", sa.BigInteger(), nullable=False),
        sa.Column("posted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("canceled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["created_by_account_id"],
            ["account.id"],
        ),
        sa.ForeignKeyConstraint(
            ["payee_organization_id"],
            ["organization.id"],
        ),
        sa.ForeignKeyConstraint(
            ["payer_organization_id"],
            ["organization.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("payment_number"),
    )
    op.create_index(
        op.f("ix_payment_payee_organization_id"),
        "payment",
        ["payee_organization_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_payment_payer_organization_id"),
        "payment",
        ["payer_organization_id"],
        unique=False,
    )
    op.create_index(op.f("ix_payment_status"), "payment", ["status"], unique=False)
    op.create_table(
        "purchase_order",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("purchase_order_number", sa.String(length=50), nullable=False),
        sa.Column("buyer_organization_id", sa.BigInteger(), nullable=False),
        sa.Column("supplier_organization_id", sa.BigInteger(), nullable=False),
        sa.Column("warehouse_id", sa.BigInteger(), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("order_date", sa.Date(), nullable=False),
        sa.Column("expected_date", sa.Date(), nullable=True),
        sa.Column("subtotal", sa.Numeric(precision=16, scale=2), nullable=False),
        sa.Column("tax_amount", sa.Numeric(precision=16, scale=2), nullable=False),
        sa.Column("total_amount", sa.Numeric(precision=16, scale=2), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("created_by_account_id", sa.BigInteger(), nullable=False),
        sa.Column("approved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("canceled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["buyer_organization_id"],
            ["organization.id"],
        ),
        sa.ForeignKeyConstraint(
            ["created_by_account_id"],
            ["account.id"],
        ),
        sa.ForeignKeyConstraint(
            ["supplier_organization_id"],
            ["organization.id"],
        ),
        sa.ForeignKeyConstraint(
            ["warehouse_id"],
            ["warehouse.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("purchase_order_number"),
    )
    op.create_index(
        op.f("ix_purchase_order_buyer_organization_id"),
        "purchase_order",
        ["buyer_organization_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_purchase_order_status"), "purchase_order", ["status"], unique=False
    )
    op.create_index(
        op.f("ix_purchase_order_supplier_organization_id"),
        "purchase_order",
        ["supplier_organization_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_purchase_order_warehouse_id"),
        "purchase_order",
        ["warehouse_id"],
        unique=False,
    )
    op.create_table(
        "goods_receipt",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("receipt_number", sa.String(length=50), nullable=False),
        sa.Column("purchase_order_id", sa.BigInteger(), nullable=False),
        sa.Column("warehouse_id", sa.BigInteger(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("received_date", sa.Date(), nullable=False),
        sa.Column("supplier_reference", sa.String(length=100), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("received_by_account_id", sa.BigInteger(), nullable=False),
        sa.Column("posted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["purchase_order_id"],
            ["purchase_order.id"],
        ),
        sa.ForeignKeyConstraint(
            ["received_by_account_id"],
            ["account.id"],
        ),
        sa.ForeignKeyConstraint(
            ["warehouse_id"],
            ["warehouse.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("receipt_number"),
    )
    op.create_index(
        op.f("ix_goods_receipt_purchase_order_id"),
        "goods_receipt",
        ["purchase_order_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_goods_receipt_status"), "goods_receipt", ["status"], unique=False
    )
    op.create_index(
        op.f("ix_goods_receipt_warehouse_id"),
        "goods_receipt",
        ["warehouse_id"],
        unique=False,
    )
    op.create_table(
        "invoice",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("invoice_number", sa.String(length=50), nullable=False),
        sa.Column("seller_organization_id", sa.BigInteger(), nullable=False),
        sa.Column("customer_organization_id", sa.BigInteger(), nullable=False),
        sa.Column("order_id", sa.BigInteger(), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("issue_date", sa.Date(), nullable=False),
        sa.Column("due_date", sa.Date(), nullable=False),
        sa.Column("subtotal", sa.Numeric(precision=16, scale=2), nullable=False),
        sa.Column("tax_amount", sa.Numeric(precision=16, scale=2), nullable=False),
        sa.Column("total_amount", sa.Numeric(precision=16, scale=2), nullable=False),
        sa.Column("paid_amount", sa.Numeric(precision=16, scale=2), nullable=False),
        sa.Column("created_by_account_id", sa.BigInteger(), nullable=False),
        sa.Column("issued_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("voided_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["created_by_account_id"],
            ["account.id"],
        ),
        sa.ForeignKeyConstraint(
            ["customer_organization_id"],
            ["organization.id"],
        ),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["sales_order.id"],
        ),
        sa.ForeignKeyConstraint(
            ["seller_organization_id"],
            ["organization.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("invoice_number"),
    )
    op.create_index(
        op.f("ix_invoice_customer_organization_id"),
        "invoice",
        ["customer_organization_id"],
        unique=False,
    )
    op.create_index(op.f("ix_invoice_order_id"), "invoice", ["order_id"], unique=False)
    op.create_index(
        op.f("ix_invoice_seller_organization_id"),
        "invoice",
        ["seller_organization_id"],
        unique=False,
    )
    op.create_index(op.f("ix_invoice_status"), "invoice", ["status"], unique=False)
    op.create_table(
        "purchase_order_status_history",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("purchase_order_id", sa.BigInteger(), nullable=False),
        sa.Column("from_status", sa.String(length=30), nullable=True),
        sa.Column("to_status", sa.String(length=30), nullable=False),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("changed_by_account_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "changed_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["changed_by_account_id"],
            ["account.id"],
        ),
        sa.ForeignKeyConstraint(
            ["purchase_order_id"],
            ["purchase_order.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_purchase_order_status_history_purchase_order_id"),
        "purchase_order_status_history",
        ["purchase_order_id"],
        unique=False,
    )
    op.create_table(
        "reorder_policy",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("warehouse_id", sa.BigInteger(), nullable=False),
        sa.Column("product_id", sa.BigInteger(), nullable=False),
        sa.Column("preferred_supplier_organization_id", sa.BigInteger(), nullable=True),
        sa.Column("reorder_point", sa.Integer(), nullable=False),
        sa.Column("target_stock_quantity", sa.Integer(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["preferred_supplier_organization_id"],
            ["organization.id"],
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["product.id"],
        ),
        sa.ForeignKeyConstraint(
            ["warehouse_id"],
            ["warehouse.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("warehouse_id", "product_id", name="uq_reorder_policy"),
    )
    op.create_index(
        op.f("ix_reorder_policy_product_id"),
        "reorder_policy",
        ["product_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_reorder_policy_warehouse_id"),
        "reorder_policy",
        ["warehouse_id"],
        unique=False,
    )
    op.create_table(
        "sales_return",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("return_number", sa.String(length=50), nullable=False),
        sa.Column("order_id", sa.BigInteger(), nullable=False),
        sa.Column("customer_organization_id", sa.BigInteger(), nullable=False),
        sa.Column("warehouse_id", sa.BigInteger(), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("reason", sa.String(length=100), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column(
            "requested_credit_amount", sa.Numeric(precision=16, scale=2), nullable=False
        ),
        sa.Column("requested_by_account_id", sa.BigInteger(), nullable=False),
        sa.Column("approved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("canceled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["customer_organization_id"],
            ["organization.id"],
        ),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["sales_order.id"],
        ),
        sa.ForeignKeyConstraint(
            ["requested_by_account_id"],
            ["account.id"],
        ),
        sa.ForeignKeyConstraint(
            ["warehouse_id"],
            ["warehouse.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("return_number"),
    )
    op.create_index(
        op.f("ix_sales_return_customer_organization_id"),
        "sales_return",
        ["customer_organization_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_sales_return_order_id"), "sales_return", ["order_id"], unique=False
    )
    op.create_index(
        op.f("ix_sales_return_status"), "sales_return", ["status"], unique=False
    )
    op.create_index(
        op.f("ix_sales_return_warehouse_id"),
        "sales_return",
        ["warehouse_id"],
        unique=False,
    )
    op.create_table(
        "supplier_product",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("supplier_organization_id", sa.BigInteger(), nullable=False),
        sa.Column("product_id", sa.BigInteger(), nullable=False),
        sa.Column("supplier_sku", sa.String(length=80), nullable=False),
        sa.Column("unit_cost", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("lead_time_days", sa.Integer(), nullable=False),
        sa.Column("minimum_order_quantity", sa.Integer(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["product.id"],
        ),
        sa.ForeignKeyConstraint(
            ["supplier_organization_id"],
            ["organization.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "supplier_organization_id", "product_id", name="uq_supplier_product"
        ),
    )
    op.create_index(
        op.f("ix_supplier_product_product_id"),
        "supplier_product",
        ["product_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_supplier_product_supplier_organization_id"),
        "supplier_product",
        ["supplier_organization_id"],
        unique=False,
    )
    op.create_table(
        "goods_receipt_status_history",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("goods_receipt_id", sa.BigInteger(), nullable=False),
        sa.Column("from_status", sa.String(length=20), nullable=True),
        sa.Column("to_status", sa.String(length=20), nullable=False),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("changed_by_account_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "changed_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["changed_by_account_id"],
            ["account.id"],
        ),
        sa.ForeignKeyConstraint(
            ["goods_receipt_id"],
            ["goods_receipt.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_goods_receipt_status_history_goods_receipt_id"),
        "goods_receipt_status_history",
        ["goods_receipt_id"],
        unique=False,
    )
    op.create_table(
        "invoice_status_history",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("invoice_id", sa.BigInteger(), nullable=False),
        sa.Column("from_status", sa.String(length=30), nullable=True),
        sa.Column("to_status", sa.String(length=30), nullable=False),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("changed_by_account_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "changed_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["changed_by_account_id"],
            ["account.id"],
        ),
        sa.ForeignKeyConstraint(
            ["invoice_id"],
            ["invoice.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_invoice_status_history_invoice_id"),
        "invoice_status_history",
        ["invoice_id"],
        unique=False,
    )
    op.create_table(
        "payment_allocation",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("payment_id", sa.BigInteger(), nullable=False),
        sa.Column("invoice_id", sa.BigInteger(), nullable=False),
        sa.Column("amount", sa.Numeric(precision=16, scale=2), nullable=False),
        sa.Column("allocated_by_account_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["allocated_by_account_id"],
            ["account.id"],
        ),
        sa.ForeignKeyConstraint(
            ["invoice_id"],
            ["invoice.id"],
        ),
        sa.ForeignKeyConstraint(
            ["payment_id"],
            ["payment.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("payment_id", "invoice_id", name="uq_payment_invoice"),
    )
    op.create_index(
        op.f("ix_payment_allocation_invoice_id"),
        "payment_allocation",
        ["invoice_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_payment_allocation_payment_id"),
        "payment_allocation",
        ["payment_id"],
        unique=False,
    )
    op.create_table(
        "purchase_order_item",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("purchase_order_id", sa.BigInteger(), nullable=False),
        sa.Column("product_id", sa.BigInteger(), nullable=False),
        sa.Column("supplier_product_id", sa.BigInteger(), nullable=True),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("received_quantity", sa.Integer(), nullable=False),
        sa.Column("unit_cost", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("subtotal", sa.Numeric(precision=16, scale=2), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("quantity > 0", name="ck_purchase_order_item_quantity"),
        sa.CheckConstraint(
            "received_quantity >= 0 AND received_quantity <= quantity",
            name="ck_purchase_order_item_received",
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["product.id"],
        ),
        sa.ForeignKeyConstraint(
            ["purchase_order_id"],
            ["purchase_order.id"],
        ),
        sa.ForeignKeyConstraint(
            ["supplier_product_id"],
            ["supplier_product.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "purchase_order_id", "product_id", name="uq_purchase_order_product"
        ),
    )
    op.create_index(
        op.f("ix_purchase_order_item_product_id"),
        "purchase_order_item",
        ["product_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_purchase_order_item_purchase_order_id"),
        "purchase_order_item",
        ["purchase_order_id"],
        unique=False,
    )
    op.create_table(
        "return_receipt",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("receipt_number", sa.String(length=50), nullable=False),
        sa.Column("sales_return_id", sa.BigInteger(), nullable=False),
        sa.Column("warehouse_id", sa.BigInteger(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("received_by_account_id", sa.BigInteger(), nullable=False),
        sa.Column("posted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["received_by_account_id"],
            ["account.id"],
        ),
        sa.ForeignKeyConstraint(
            ["sales_return_id"],
            ["sales_return.id"],
        ),
        sa.ForeignKeyConstraint(
            ["warehouse_id"],
            ["warehouse.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("receipt_number"),
    )
    op.create_index(
        op.f("ix_return_receipt_sales_return_id"),
        "return_receipt",
        ["sales_return_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_return_receipt_status"), "return_receipt", ["status"], unique=False
    )
    op.create_index(
        op.f("ix_return_receipt_warehouse_id"),
        "return_receipt",
        ["warehouse_id"],
        unique=False,
    )
    op.create_table(
        "sales_return_item",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("sales_return_id", sa.BigInteger(), nullable=False),
        sa.Column("order_item_id", sa.BigInteger(), nullable=False),
        sa.Column("product_id", sa.BigInteger(), nullable=False),
        sa.Column("requested_quantity", sa.Integer(), nullable=False),
        sa.Column("received_quantity", sa.Integer(), nullable=False),
        sa.Column("restocked_quantity", sa.Integer(), nullable=False),
        sa.Column("discarded_quantity", sa.Integer(), nullable=False),
        sa.Column("unit_credit", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "received_quantity >= 0 AND received_quantity <= requested_quantity",
            name="ck_sales_return_item_received",
        ),
        sa.CheckConstraint(
            "requested_quantity > 0", name="ck_sales_return_item_quantity"
        ),
        sa.ForeignKeyConstraint(
            ["order_item_id"],
            ["sales_order_item.id"],
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["product.id"],
        ),
        sa.ForeignKeyConstraint(
            ["sales_return_id"],
            ["sales_return.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "sales_return_id", "order_item_id", name="uq_sales_return_order_item"
        ),
    )
    op.create_index(
        op.f("ix_sales_return_item_order_item_id"),
        "sales_return_item",
        ["order_item_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_sales_return_item_product_id"),
        "sales_return_item",
        ["product_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_sales_return_item_sales_return_id"),
        "sales_return_item",
        ["sales_return_id"],
        unique=False,
    )
    op.create_table(
        "sales_return_status_history",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("sales_return_id", sa.BigInteger(), nullable=False),
        sa.Column("from_status", sa.String(length=30), nullable=True),
        sa.Column("to_status", sa.String(length=30), nullable=False),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("changed_by_account_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "changed_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["changed_by_account_id"],
            ["account.id"],
        ),
        sa.ForeignKeyConstraint(
            ["sales_return_id"],
            ["sales_return.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_sales_return_status_history_sales_return_id"),
        "sales_return_status_history",
        ["sales_return_id"],
        unique=False,
    )
    op.create_table(
        "goods_receipt_item",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("goods_receipt_id", sa.BigInteger(), nullable=False),
        sa.Column("purchase_order_item_id", sa.BigInteger(), nullable=False),
        sa.Column("product_id", sa.BigInteger(), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("accepted_quantity", sa.Integer(), nullable=False),
        sa.Column("rejected_quantity", sa.Integer(), nullable=False),
        sa.Column("rejection_reason", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "accepted_quantity + rejected_quantity = quantity",
            name="ck_goods_receipt_disposition",
        ),
        sa.CheckConstraint("quantity > 0", name="ck_goods_receipt_quantity"),
        sa.ForeignKeyConstraint(
            ["goods_receipt_id"],
            ["goods_receipt.id"],
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["product.id"],
        ),
        sa.ForeignKeyConstraint(
            ["purchase_order_item_id"],
            ["purchase_order_item.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "goods_receipt_id",
            "purchase_order_item_id",
            name="uq_goods_receipt_order_item",
        ),
    )
    op.create_index(
        op.f("ix_goods_receipt_item_goods_receipt_id"),
        "goods_receipt_item",
        ["goods_receipt_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_goods_receipt_item_product_id"),
        "goods_receipt_item",
        ["product_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_goods_receipt_item_purchase_order_item_id"),
        "goods_receipt_item",
        ["purchase_order_item_id"],
        unique=False,
    )
    op.create_table(
        "invoice_item",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("invoice_id", sa.BigInteger(), nullable=False),
        sa.Column("order_item_id", sa.BigInteger(), nullable=True),
        sa.Column("shipment_item_id", sa.BigInteger(), nullable=True),
        sa.Column("product_id", sa.BigInteger(), nullable=False),
        sa.Column("description", sa.String(length=250), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("unit_price", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("subtotal", sa.Numeric(precision=16, scale=2), nullable=False),
        sa.Column("tax_amount", sa.Numeric(precision=16, scale=2), nullable=False),
        sa.Column("total_amount", sa.Numeric(precision=16, scale=2), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["invoice_id"],
            ["invoice.id"],
        ),
        sa.ForeignKeyConstraint(
            ["order_item_id"],
            ["sales_order_item.id"],
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["product.id"],
        ),
        sa.ForeignKeyConstraint(
            ["shipment_item_id"],
            ["shipment_item.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_invoice_item_invoice_id"), "invoice_item", ["invoice_id"], unique=False
    )
    op.create_index(
        op.f("ix_invoice_item_order_item_id"),
        "invoice_item",
        ["order_item_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_invoice_item_product_id"), "invoice_item", ["product_id"], unique=False
    )
    op.create_index(
        op.f("ix_invoice_item_shipment_item_id"),
        "invoice_item",
        ["shipment_item_id"],
        unique=False,
    )
    op.create_table(
        "return_receipt_item",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("return_receipt_id", sa.BigInteger(), nullable=False),
        sa.Column("sales_return_item_id", sa.BigInteger(), nullable=False),
        sa.Column("product_id", sa.BigInteger(), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("disposition", sa.String(length=20), nullable=False),
        sa.Column("condition_note", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("quantity > 0", name="ck_return_receipt_item_quantity"),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["product.id"],
        ),
        sa.ForeignKeyConstraint(
            ["return_receipt_id"],
            ["return_receipt.id"],
        ),
        sa.ForeignKeyConstraint(
            ["sales_return_item_id"],
            ["sales_return_item.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "return_receipt_id", "sales_return_item_id", name="uq_return_receipt_item"
        ),
    )
    op.create_index(
        op.f("ix_return_receipt_item_product_id"),
        "return_receipt_item",
        ["product_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_return_receipt_item_return_receipt_id"),
        "return_receipt_item",
        ["return_receipt_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_return_receipt_item_sales_return_item_id"),
        "return_receipt_item",
        ["sales_return_item_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_return_receipt_item_sales_return_item_id"),
        table_name="return_receipt_item",
    )
    op.drop_index(
        op.f("ix_return_receipt_item_return_receipt_id"),
        table_name="return_receipt_item",
    )
    op.drop_index(
        op.f("ix_return_receipt_item_product_id"), table_name="return_receipt_item"
    )
    op.drop_table("return_receipt_item")
    op.drop_index(op.f("ix_invoice_item_shipment_item_id"), table_name="invoice_item")
    op.drop_index(op.f("ix_invoice_item_product_id"), table_name="invoice_item")
    op.drop_index(op.f("ix_invoice_item_order_item_id"), table_name="invoice_item")
    op.drop_index(op.f("ix_invoice_item_invoice_id"), table_name="invoice_item")
    op.drop_table("invoice_item")
    op.drop_index(
        op.f("ix_goods_receipt_item_purchase_order_item_id"),
        table_name="goods_receipt_item",
    )
    op.drop_index(
        op.f("ix_goods_receipt_item_product_id"), table_name="goods_receipt_item"
    )
    op.drop_index(
        op.f("ix_goods_receipt_item_goods_receipt_id"), table_name="goods_receipt_item"
    )
    op.drop_table("goods_receipt_item")
    op.drop_index(
        op.f("ix_sales_return_status_history_sales_return_id"),
        table_name="sales_return_status_history",
    )
    op.drop_table("sales_return_status_history")
    op.drop_index(
        op.f("ix_sales_return_item_sales_return_id"), table_name="sales_return_item"
    )
    op.drop_index(
        op.f("ix_sales_return_item_product_id"), table_name="sales_return_item"
    )
    op.drop_index(
        op.f("ix_sales_return_item_order_item_id"), table_name="sales_return_item"
    )
    op.drop_table("sales_return_item")
    op.drop_index(op.f("ix_return_receipt_warehouse_id"), table_name="return_receipt")
    op.drop_index(op.f("ix_return_receipt_status"), table_name="return_receipt")
    op.drop_index(
        op.f("ix_return_receipt_sales_return_id"), table_name="return_receipt"
    )
    op.drop_table("return_receipt")
    op.drop_index(
        op.f("ix_purchase_order_item_purchase_order_id"),
        table_name="purchase_order_item",
    )
    op.drop_index(
        op.f("ix_purchase_order_item_product_id"), table_name="purchase_order_item"
    )
    op.drop_table("purchase_order_item")
    op.drop_index(
        op.f("ix_payment_allocation_payment_id"), table_name="payment_allocation"
    )
    op.drop_index(
        op.f("ix_payment_allocation_invoice_id"), table_name="payment_allocation"
    )
    op.drop_table("payment_allocation")
    op.drop_index(
        op.f("ix_invoice_status_history_invoice_id"),
        table_name="invoice_status_history",
    )
    op.drop_table("invoice_status_history")
    op.drop_index(
        op.f("ix_goods_receipt_status_history_goods_receipt_id"),
        table_name="goods_receipt_status_history",
    )
    op.drop_table("goods_receipt_status_history")
    op.drop_index(
        op.f("ix_supplier_product_supplier_organization_id"),
        table_name="supplier_product",
    )
    op.drop_index(op.f("ix_supplier_product_product_id"), table_name="supplier_product")
    op.drop_table("supplier_product")
    op.drop_index(op.f("ix_sales_return_warehouse_id"), table_name="sales_return")
    op.drop_index(op.f("ix_sales_return_status"), table_name="sales_return")
    op.drop_index(op.f("ix_sales_return_order_id"), table_name="sales_return")
    op.drop_index(
        op.f("ix_sales_return_customer_organization_id"), table_name="sales_return"
    )
    op.drop_table("sales_return")
    op.drop_index(op.f("ix_reorder_policy_warehouse_id"), table_name="reorder_policy")
    op.drop_index(op.f("ix_reorder_policy_product_id"), table_name="reorder_policy")
    op.drop_table("reorder_policy")
    op.drop_index(
        op.f("ix_purchase_order_status_history_purchase_order_id"),
        table_name="purchase_order_status_history",
    )
    op.drop_table("purchase_order_status_history")
    op.drop_index(op.f("ix_invoice_status"), table_name="invoice")
    op.drop_index(op.f("ix_invoice_seller_organization_id"), table_name="invoice")
    op.drop_index(op.f("ix_invoice_order_id"), table_name="invoice")
    op.drop_index(op.f("ix_invoice_customer_organization_id"), table_name="invoice")
    op.drop_table("invoice")
    op.drop_index(op.f("ix_goods_receipt_warehouse_id"), table_name="goods_receipt")
    op.drop_index(op.f("ix_goods_receipt_status"), table_name="goods_receipt")
    op.drop_index(
        op.f("ix_goods_receipt_purchase_order_id"), table_name="goods_receipt"
    )
    op.drop_table("goods_receipt")
    op.drop_index(op.f("ix_purchase_order_warehouse_id"), table_name="purchase_order")
    op.drop_index(
        op.f("ix_purchase_order_supplier_organization_id"), table_name="purchase_order"
    )
    op.drop_index(op.f("ix_purchase_order_status"), table_name="purchase_order")
    op.drop_index(
        op.f("ix_purchase_order_buyer_organization_id"), table_name="purchase_order"
    )
    op.drop_table("purchase_order")
    op.drop_index(op.f("ix_payment_status"), table_name="payment")
    op.drop_index(op.f("ix_payment_payer_organization_id"), table_name="payment")
    op.drop_index(op.f("ix_payment_payee_organization_id"), table_name="payment")
    op.drop_table("payment")
    # ### end Alembic commands ###
