"""add_b2b_order_fulfillment

Revision ID: 815dac684b5d
Revises: 3f43b8fa0610
Create Date: 2026-08-17 17:28:50.753516

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '815dac684b5d'
down_revision: Union[str, Sequence[str], None] = '3f43b8fa0610'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organization',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('outbox_event',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('aggregate_type', sa.String(length=50), nullable=False),
    sa.Column('aggregate_id', sa.BigInteger(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('available_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_outbox_event_event_type'), 'outbox_event', ['event_type'], unique=False)
    op.create_index(op.f('ix_outbox_event_status'), 'outbox_event', ['status'], unique=False)
    op.create_table('audit_log',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('actor_account_id', sa.BigInteger(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('resource_type', sa.String(length=50), nullable=False),
    sa.Column('resource_id', sa.BigInteger(), nullable=False),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_account_id'], ['account.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_log_action'), 'audit_log', ['action'], unique=False)
    op.create_index(op.f('ix_audit_log_actor_account_id'), 'audit_log', ['actor_account_id'], unique=False)
    op.create_index(op.f('ix_audit_log_created_at'), 'audit_log', ['created_at'], unique=False)
    op.create_table('organization_address',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('organization_id', sa.BigInteger(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('postal_code', sa.String(length=20), nullable=False),
    sa.Column('prefecture', sa.String(length=100), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('address_line1', sa.String(length=200), nullable=False),
    sa.Column('address_line2', sa.String(length=200), nullable=True),
    sa.Column('recipient_name', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organization_address_organization_id'), 'organization_address', ['organization_id'], unique=False)
    op.create_table('organization_member',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('organization_id', sa.BigInteger(), nullable=False),
    sa.Column('account_id', sa.BigInteger(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'account_id', name='uq_organization_member')
    )
    op.create_index(op.f('ix_organization_member_account_id'), 'organization_member', ['account_id'], unique=False)
    op.create_index(op.f('ix_organization_member_organization_id'), 'organization_member', ['organization_id'], unique=False)
    op.create_table('product_category',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('organization_id', sa.BigInteger(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'code', name='uq_product_category_code')
    )
    op.create_index(op.f('ix_product_category_organization_id'), 'product_category', ['organization_id'], unique=False)
    op.create_table('warehouse',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('organization_id', sa.BigInteger(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'code', name='uq_warehouse_code')
    )
    op.create_index(op.f('ix_warehouse_organization_id'), 'warehouse', ['organization_id'], unique=False)
    op.create_table('inventory_adjustment',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('warehouse_id', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('created_by_account_id', sa.BigInteger(), nullable=False),
    sa.Column('applied_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_account_id'], ['account.id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouse.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventory_adjustment_warehouse_id'), 'inventory_adjustment', ['warehouse_id'], unique=False)
    op.create_table('inventory_transfer',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('source_warehouse_id', sa.BigInteger(), nullable=False),
    sa.Column('destination_warehouse_id', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_by_account_id', sa.BigInteger(), nullable=False),
    sa.Column('shipped_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_account_id'], ['account.id'], ),
    sa.ForeignKeyConstraint(['destination_warehouse_id'], ['warehouse.id'], ),
    sa.ForeignKeyConstraint(['source_warehouse_id'], ['warehouse.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventory_transfer_destination_warehouse_id'), 'inventory_transfer', ['destination_warehouse_id'], unique=False)
    op.create_index(op.f('ix_inventory_transfer_source_warehouse_id'), 'inventory_transfer', ['source_warehouse_id'], unique=False)
    op.create_table('product',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('organization_id', sa.BigInteger(), nullable=False),
    sa.Column('category_id', sa.BigInteger(), nullable=True),
    sa.Column('sku', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('unit_price', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['product_category.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'sku', name='uq_product_sku')
    )
    op.create_index(op.f('ix_product_category_id'), 'product', ['category_id'], unique=False)
    op.create_index(op.f('ix_product_organization_id'), 'product', ['organization_id'], unique=False)
    op.create_table('sales_order',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('order_number', sa.String(length=50), nullable=False),
    sa.Column('seller_organization_id', sa.BigInteger(), nullable=False),
    sa.Column('customer_organization_id', sa.BigInteger(), nullable=False),
    sa.Column('shipping_address_id', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('requested_ship_date', sa.Date(), nullable=True),
    sa.Column('subtotal', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('tax_amount', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('ordered_by_account_id', sa.BigInteger(), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('canceled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_organization_id'], ['organization.id'], ),
    sa.ForeignKeyConstraint(['ordered_by_account_id'], ['account.id'], ),
    sa.ForeignKeyConstraint(['seller_organization_id'], ['organization.id'], ),
    sa.ForeignKeyConstraint(['shipping_address_id'], ['organization_address.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_number')
    )
    op.create_index(op.f('ix_sales_order_customer_organization_id'), 'sales_order', ['customer_organization_id'], unique=False)
    op.create_index(op.f('ix_sales_order_seller_organization_id'), 'sales_order', ['seller_organization_id'], unique=False)
    op.create_index(op.f('ix_sales_order_status'), 'sales_order', ['status'], unique=False)
    op.create_table('customer_product_price',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('customer_organization_id', sa.BigInteger(), nullable=False),
    sa.Column('product_id', sa.BigInteger(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('valid_from', sa.Date(), nullable=False),
    sa.Column('valid_to', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_organization_id'], ['organization.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customer_product_price_customer_organization_id'), 'customer_product_price', ['customer_organization_id'], unique=False)
    op.create_index(op.f('ix_customer_product_price_product_id'), 'customer_product_price', ['product_id'], unique=False)
    op.create_table('inventory_adjustment_item',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('adjustment_id', sa.BigInteger(), nullable=False),
    sa.Column('product_id', sa.BigInteger(), nullable=False),
    sa.Column('quantity_delta', sa.Integer(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['adjustment_id'], ['inventory_adjustment.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventory_adjustment_item_adjustment_id'), 'inventory_adjustment_item', ['adjustment_id'], unique=False)
    op.create_index(op.f('ix_inventory_adjustment_item_product_id'), 'inventory_adjustment_item', ['product_id'], unique=False)
    op.create_table('inventory_balance',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('warehouse_id', sa.BigInteger(), nullable=False),
    sa.Column('product_id', sa.BigInteger(), nullable=False),
    sa.Column('on_hand_quantity', sa.Integer(), nullable=False),
    sa.Column('reserved_quantity', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('on_hand_quantity >= 0', name='ck_inventory_on_hand_nonnegative'),
    sa.CheckConstraint('reserved_quantity <= on_hand_quantity', name='ck_inventory_reserved_within_on_hand'),
    sa.CheckConstraint('reserved_quantity >= 0', name='ck_inventory_reserved_nonnegative'),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouse.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('warehouse_id', 'product_id', name='uq_inventory_balance')
    )
    op.create_index(op.f('ix_inventory_balance_product_id'), 'inventory_balance', ['product_id'], unique=False)
    op.create_index(op.f('ix_inventory_balance_warehouse_id'), 'inventory_balance', ['warehouse_id'], unique=False)
    op.create_table('inventory_ledger',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('warehouse_id', sa.BigInteger(), nullable=False),
    sa.Column('product_id', sa.BigInteger(), nullable=False),
    sa.Column('event_type', sa.String(length=30), nullable=False),
    sa.Column('on_hand_delta', sa.Integer(), nullable=False),
    sa.Column('reserved_delta', sa.Integer(), nullable=False),
    sa.Column('on_hand_after', sa.Integer(), nullable=False),
    sa.Column('reserved_after', sa.Integer(), nullable=False),
    sa.Column('reference_type', sa.String(length=40), nullable=False),
    sa.Column('reference_id', sa.BigInteger(), nullable=False),
    sa.Column('actor_account_id', sa.BigInteger(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_account_id'], ['account.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouse.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventory_ledger_actor_account_id'), 'inventory_ledger', ['actor_account_id'], unique=False)
    op.create_index(op.f('ix_inventory_ledger_occurred_at'), 'inventory_ledger', ['occurred_at'], unique=False)
    op.create_index(op.f('ix_inventory_ledger_product_id'), 'inventory_ledger', ['product_id'], unique=False)
    op.create_index(op.f('ix_inventory_ledger_warehouse_id'), 'inventory_ledger', ['warehouse_id'], unique=False)
    op.create_table('inventory_transfer_item',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('transfer_id', sa.BigInteger(), nullable=False),
    sa.Column('product_id', sa.BigInteger(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.ForeignKeyConstraint(['transfer_id'], ['inventory_transfer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventory_transfer_item_product_id'), 'inventory_transfer_item', ['product_id'], unique=False)
    op.create_index(op.f('ix_inventory_transfer_item_transfer_id'), 'inventory_transfer_item', ['transfer_id'], unique=False)
    op.create_table('sales_order_item',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.BigInteger(), nullable=False),
    sa.Column('product_id', sa.BigInteger(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['sales_order.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_id', 'product_id', name='uq_order_product')
    )
    op.create_index(op.f('ix_sales_order_item_order_id'), 'sales_order_item', ['order_id'], unique=False)
    op.create_index(op.f('ix_sales_order_item_product_id'), 'sales_order_item', ['product_id'], unique=False)
    op.create_table('sales_order_status_history',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.BigInteger(), nullable=False),
    sa.Column('from_status', sa.String(length=30), nullable=True),
    sa.Column('to_status', sa.String(length=30), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('changed_by_account_id', sa.BigInteger(), nullable=False),
    sa.Column('changed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['changed_by_account_id'], ['account.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['sales_order.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sales_order_status_history_order_id'), 'sales_order_status_history', ['order_id'], unique=False)
    op.create_table('shipment',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('shipment_number', sa.String(length=50), nullable=False),
    sa.Column('order_id', sa.BigInteger(), nullable=False),
    sa.Column('warehouse_id', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('tracking_number', sa.String(length=100), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_by_account_id', sa.BigInteger(), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('shipped_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_account_id'], ['account.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['sales_order.id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouse.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('shipment_number')
    )
    op.create_index(op.f('ix_shipment_order_id'), 'shipment', ['order_id'], unique=False)
    op.create_index(op.f('ix_shipment_status'), 'shipment', ['status'], unique=False)
    op.create_index(op.f('ix_shipment_warehouse_id'), 'shipment', ['warehouse_id'], unique=False)
    op.create_table('shipment_item',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('shipment_id', sa.BigInteger(), nullable=False),
    sa.Column('order_item_id', sa.BigInteger(), nullable=False),
    sa.Column('product_id', sa.BigInteger(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['order_item_id'], ['sales_order_item.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipment.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('shipment_id', 'order_item_id', name='uq_shipment_order_item')
    )
    op.create_index(op.f('ix_shipment_item_order_item_id'), 'shipment_item', ['order_item_id'], unique=False)
    op.create_index(op.f('ix_shipment_item_product_id'), 'shipment_item', ['product_id'], unique=False)
    op.create_index(op.f('ix_shipment_item_shipment_id'), 'shipment_item', ['shipment_id'], unique=False)
    op.create_table('shipment_status_history',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('shipment_id', sa.BigInteger(), nullable=False),
    sa.Column('from_status', sa.String(length=20), nullable=True),
    sa.Column('to_status', sa.String(length=20), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('changed_by_account_id', sa.BigInteger(), nullable=False),
    sa.Column('changed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['changed_by_account_id'], ['account.id'], ),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipment.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shipment_status_history_shipment_id'), 'shipment_status_history', ['shipment_id'], unique=False)
    op.create_table('stock_reservation',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('order_item_id', sa.BigInteger(), nullable=False),
    sa.Column('warehouse_id', sa.BigInteger(), nullable=False),
    sa.Column('product_id', sa.BigInteger(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['order_item_id'], ['sales_order_item.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouse.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stock_reservation_order_item_id'), 'stock_reservation', ['order_item_id'], unique=False)
    op.create_index(op.f('ix_stock_reservation_product_id'), 'stock_reservation', ['product_id'], unique=False)
    op.create_index(op.f('ix_stock_reservation_status'), 'stock_reservation', ['status'], unique=False)
    op.create_index(op.f('ix_stock_reservation_warehouse_id'), 'stock_reservation', ['warehouse_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stock_reservation_warehouse_id'), table_name='stock_reservation')
    op.drop_index(op.f('ix_stock_reservation_status'), table_name='stock_reservation')
    op.drop_index(op.f('ix_stock_reservation_product_id'), table_name='stock_reservation')
    op.drop_index(op.f('ix_stock_reservation_order_item_id'), table_name='stock_reservation')
    op.drop_table('stock_reservation')
    op.drop_index(op.f('ix_shipment_status_history_shipment_id'), table_name='shipment_status_history')
    op.drop_table('shipment_status_history')
    op.drop_index(op.f('ix_shipment_item_shipment_id'), table_name='shipment_item')
    op.drop_index(op.f('ix_shipment_item_product_id'), table_name='shipment_item')
    op.drop_index(op.f('ix_shipment_item_order_item_id'), table_name='shipment_item')
    op.drop_table('shipment_item')
    op.drop_index(op.f('ix_shipment_warehouse_id'), table_name='shipment')
    op.drop_index(op.f('ix_shipment_status'), table_name='shipment')
    op.drop_index(op.f('ix_shipment_order_id'), table_name='shipment')
    op.drop_table('shipment')
    op.drop_index(op.f('ix_sales_order_status_history_order_id'), table_name='sales_order_status_history')
    op.drop_table('sales_order_status_history')
    op.drop_index(op.f('ix_sales_order_item_product_id'), table_name='sales_order_item')
    op.drop_index(op.f('ix_sales_order_item_order_id'), table_name='sales_order_item')
    op.drop_table('sales_order_item')
    op.drop_index(op.f('ix_inventory_transfer_item_transfer_id'), table_name='inventory_transfer_item')
    op.drop_index(op.f('ix_inventory_transfer_item_product_id'), table_name='inventory_transfer_item')
    op.drop_table('inventory_transfer_item')
    op.drop_index(op.f('ix_inventory_ledger_warehouse_id'), table_name='inventory_ledger')
    op.drop_index(op.f('ix_inventory_ledger_product_id'), table_name='inventory_ledger')
    op.drop_index(op.f('ix_inventory_ledger_occurred_at'), table_name='inventory_ledger')
    op.drop_index(op.f('ix_inventory_ledger_actor_account_id'), table_name='inventory_ledger')
    op.drop_table('inventory_ledger')
    op.drop_index(op.f('ix_inventory_balance_warehouse_id'), table_name='inventory_balance')
    op.drop_index(op.f('ix_inventory_balance_product_id'), table_name='inventory_balance')
    op.drop_table('inventory_balance')
    op.drop_index(op.f('ix_inventory_adjustment_item_product_id'), table_name='inventory_adjustment_item')
    op.drop_index(op.f('ix_inventory_adjustment_item_adjustment_id'), table_name='inventory_adjustment_item')
    op.drop_table('inventory_adjustment_item')
    op.drop_index(op.f('ix_customer_product_price_product_id'), table_name='customer_product_price')
    op.drop_index(op.f('ix_customer_product_price_customer_organization_id'), table_name='customer_product_price')
    op.drop_table('customer_product_price')
    op.drop_index(op.f('ix_sales_order_status'), table_name='sales_order')
    op.drop_index(op.f('ix_sales_order_seller_organization_id'), table_name='sales_order')
    op.drop_index(op.f('ix_sales_order_customer_organization_id'), table_name='sales_order')
    op.drop_table('sales_order')
    op.drop_index(op.f('ix_product_organization_id'), table_name='product')
    op.drop_index(op.f('ix_product_category_id'), table_name='product')
    op.drop_table('product')
    op.drop_index(op.f('ix_inventory_transfer_source_warehouse_id'), table_name='inventory_transfer')
    op.drop_index(op.f('ix_inventory_transfer_destination_warehouse_id'), table_name='inventory_transfer')
    op.drop_table('inventory_transfer')
    op.drop_index(op.f('ix_inventory_adjustment_warehouse_id'), table_name='inventory_adjustment')
    op.drop_table('inventory_adjustment')
    op.drop_index(op.f('ix_warehouse_organization_id'), table_name='warehouse')
    op.drop_table('warehouse')
    op.drop_index(op.f('ix_product_category_organization_id'), table_name='product_category')
    op.drop_table('product_category')
    op.drop_index(op.f('ix_organization_member_organization_id'), table_name='organization_member')
    op.drop_index(op.f('ix_organization_member_account_id'), table_name='organization_member')
    op.drop_table('organization_member')
    op.drop_index(op.f('ix_organization_address_organization_id'), table_name='organization_address')
    op.drop_table('organization_address')
    op.drop_index(op.f('ix_audit_log_created_at'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_actor_account_id'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_action'), table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_index(op.f('ix_outbox_event_status'), table_name='outbox_event')
    op.drop_index(op.f('ix_outbox_event_event_type'), table_name='outbox_event')
    op.drop_table('outbox_event')
    op.drop_table('organization')
    # ### end Alembic commands ###
